### ISSUE TITLE
Image normalization in the data loaders

### ISSUE THREAD

**Issue by mbsariyildiz** [chigur/byol-convert#1]
Hello!
Thanks a lot for sharing this converter!
I have a question:
It seems that in the [original implementation](https://github.com/deepmind/deepmind-research/blob/7488a1f70af89760e335a5c05afed5fe3d06a45e/byol/utils/dataset.py#L182), there is no image normalization.
However, in your [validation script](https://github.com/chigur/byol-convert/blob/3ae8e7f97e0bc6143c68527b3732847de50d9a0b/validate.py#L31), you have one.
Am I missing something?

**Comment by ajtejankar** [comment]
Hi,

The entire script is based on educated guesses since I have no clue about JAX or Haiku ;) So, although I could be wrong, they use a function called [`noramalize_images`](https://github.com/deepmind/deepmind-research/blob/486d8caf2130a90356b912d8fc146818c59b2d7f/byol/utils/dataset.py#L63) for normalizing images with ImageNet statistics. It is called from the the [function](https://github.com/deepmind/deepmind-research/blob/486d8caf2130a90356b912d8fc146818c59b2d7f/byol/eval_experiment.py#L144) that evaluates the linear layer.

**Comment by mbsariyildiz** [comment]
Hello,
Thanks for your return.
In the meantime, I simply doubled checked with/without normalization, and I was able to reproduce the results only with normalization. :)

**Comment by ajtejankar** [comment]
Great!
